### ISSUE TITLE
stage3 bootstrapping broken

### ISSUE THREAD

**Issue by thatnerdjosh** [Toasterbirb/birb#2]
Due to some of the recent changes to integrate `birb_db`, and `birb-sources.conf`, stage3 bootstrapping (downloading sources on host so deps can be downloaded) is broken.

In order to fix this, I had to point `birb` at the `LFS` prefix for finding `birb-sources.conf`, add the `LFS` prefix in `birb-sources.conf`, and comment `update_repo_path "$1"` in the `download_src` function in `birb`

Would be good to find a more long term solution than my quick hack

**Comment by Toasterbirb** [comment]
birb should now default to `$INSTALL_PREFIX/var/db/pkg` as its repository path if `/etc/birb-sources.conf` doesn't exist

haven't tested this though, so let me know if it still doesn't work
